site_name: "Kaaovo's personal website"
site_description: "Kaaovo's personal website"

theme:
  name: material
  language: zh
  palette:
    scheme: slate

extra_css:
  - stylesheets/extra.css

nav:
  - 主页: index.md
  - 课程: course/index.md
  - 友链: friends/index.md
  - 关于: about/index.md
  - 娱乐: entertainment/index.md